[package]
name = "py-rustat"
version = "0.1.0"
authors = ['Byron Howe']
edition = "2021"
license = 'MIT'
workspace = '..'

[lib]
name = "py_rustat"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module"] }
