[package]
name = "rustat-math"
version = "0.1.0"
authors = ['Byron Howe']
edition = "2021"
license = 'MIT'
workspace = '..'

[lib]
name = 'rustat_math'
path = 'src/lib.rs'

[dev-dependencies]
rustat = { version='0.1', path='../rustat' }
